# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'A1IOSCommonSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for A1IOSCommonSDK
  pod 'Purchasely', '3.7.1'
  pod 'FirebaseAnalytics'
  pod 'Firebase'
  pod 'Mixpanel-swift'
  pod 'FBSDKCoreKit'


end
